/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import CashFlowBO.FormaPagamentoBO;
import CashFlowBO.LancamentosCaixaBO;
import CashFlowBO.TipoMovimentoBO;
import ClashFlowObjeto.FormaPagamento;
import ClashFlowObjeto.LancamentosCaixa;
import ClashFlowObjeto.TipoMovimento;
import exception.CaixaFechadoException;
import exception.DAOException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Sonia
 */
public class FormNovoLancamentosCaixa extends javax.swing.JFrame {
    
    private CallbackForm<LancamentosCaixa> callbackForm;
    private FormNovaFormaPagamento formNovaFormaPagamento;
    private FormNovoTipoMovimento formNovoTipoMovimento;
     public FormNovoLancamentosCaixa()
    {
        this(null);
    }
    public FormNovoLancamentosCaixa(CallbackForm<LancamentosCaixa> callbackForm) {
        init(callbackForm);
    }
    private void init (CallbackForm<LancamentosCaixa> callbackForm) {
        initComponents();
        this.callbackForm = callbackForm;
        this.labelError.setVisible(false);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CBFormaPagamento = new javax.swing.JComboBox<>();
        txtobservacao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbNovoMovimento = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnSalvarNovoLancamento = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnAdicionaTipoMovimento = new javax.swing.JButton();
        btnAdicionaTipoPagamento = new javax.swing.JButton();
        labelError = new javax.swing.JLabel();
        txtValorLancamento = new JFormattedTextField(getFormatoMoeda());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Novo Lançamento Caixa");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Tipo do Movimento:");

        CBFormaPagamento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CBFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<FormaPagamento>(carregaFormas()));
        CBFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBFormaPagamentoActionPerformed(evt);
            }
        });

        txtobservacao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Observações:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Valor do Movimento:");

        cbNovoMovimento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbNovoMovimento.setModel(new javax.swing.DefaultComboBoxModel<TipoMovimento>(carregaMovimentos()));
        cbNovoMovimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNovoMovimentoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Forma de Pagamento:");

        btnSalvarNovoLancamento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalvarNovoLancamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btnSalvar.png"))); // NOI18N
        btnSalvarNovoLancamento.setText("Salvar");
        btnSalvarNovoLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarNovoLancamentoActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btnSair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnAdicionaTipoMovimento.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        btnAdicionaTipoMovimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MAIS.png"))); // NOI18N
        btnAdicionaTipoMovimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionaTipoMovimentoActionPerformed(evt);
            }
        });

        btnAdicionaTipoPagamento.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        btnAdicionaTipoPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MAIS.png"))); // NOI18N
        btnAdicionaTipoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionaTipoPagamentoActionPerformed(evt);
            }
        });

        txtValorLancamento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorLancamento.setText(null);
        txtValorLancamento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtValorLancamento, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtobservacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addComponent(cbNovoMovimento, javax.swing.GroupLayout.Alignment.LEADING, 0, 211, Short.MAX_VALUE)
                                    .addComponent(CBFormaPagamento, javax.swing.GroupLayout.Alignment.LEADING, 0, 211, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAdicionaTipoMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAdicionaTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGap(3, 3, 3))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnSalvarNovoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbNovoMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAdicionaTipoMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtobservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValorLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdicionaTipoPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CBFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarNovoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelError)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private TipoMovimento[] carregaMovimentos() {
        TipoMovimentoBO tipoMovimentoBO = new TipoMovimentoBO();
        List<TipoMovimento> grupos = tipoMovimentoBO.buscarTodos();
        return grupos.toArray(new TipoMovimento[grupos.size()]);
    }
    
    private FormaPagamento[] carregaFormas() {
        FormaPagamentoBO formaPagamentoBO = new FormaPagamentoBO();
        List<FormaPagamento> formas = formaPagamentoBO.buscarTodos();
        return formas.toArray(new FormaPagamento[formas.size()]);
    }
    
    private void btnSalvarNovoLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarNovoLancamentoActionPerformed
      
        LancamentosCaixa lc = new LancamentosCaixa();
        if(txtValorLancamento.getText().isEmpty())
        {
             JOptionPane.showMessageDialog(null,"Digite o valor do lançamento!") ;
        }
        else{
        lc.setFormaPagamento((FormaPagamento) CBFormaPagamento.getSelectedItem());
        lc.setTipoMovimento((TipoMovimento)cbNovoMovimento.getSelectedItem());
        lc.setObservacao(txtobservacao.getText());
        lc.setValorMovimento(Double.parseDouble(txtValorLancamento.getText()));
       
       
            try {
                LancamentosCaixaBO LancamentosCaixaBO= new LancamentosCaixaBO();
                LancamentosCaixaBO.salvar(lc);
                JOptionPane.showMessageDialog(null,"Novo movimento salvo com sucesso!");
                
                if(callbackForm !=null)
                 {
                    callbackForm.fim(lc);
               
                 }
                } catch (CaixaFechadoException ex) {
                  Logger.getLogger(FormNovoLancamentosCaixa.class.getName()).log(Level.SEVERE, null, ex);
                } catch (DAOException ex) {
                  Logger.getLogger(FormNovoLancamentosCaixa.class.getName()).log(Level.SEVERE, null, ex);
               }
        
        
        }
    }//GEN-LAST:event_btnSalvarNovoLancamentoActionPerformed
    
    
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose(); //Comando utilizado para encerrar o formulário sem encerrar a aplicação.
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAdicionaTipoMovimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionaTipoMovimentoActionPerformed
        formNovoTipoMovimento = new FormNovoTipoMovimento(this.callbackTipoMovimento());
        formNovoTipoMovimento.setVisible(true);
    }//GEN-LAST:event_btnAdicionaTipoMovimentoActionPerformed

    private void cbNovoMovimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNovoMovimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNovoMovimentoActionPerformed

    private void btnAdicionaTipoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionaTipoPagamentoActionPerformed
        
        //Instanciação do formulário de nova forma de pagamento
        formNovaFormaPagamento = new FormNovaFormaPagamento(this.callbackFormaPagamento()); 
        formNovaFormaPagamento.setVisible(true);
    }//GEN-LAST:event_btnAdicionaTipoPagamentoActionPerformed

    private void CBFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBFormaPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBFormaPagamentoActionPerformed

    private CallbackForm callbackFormaPagamento() {
        
        //Instanciando uma classe anonima
        return new CallbackForm<FormaPagamento>() {
            @Override
            public void fim(FormaPagamento formaPagamento) {
                formNovaFormaPagamento.setVisible(false);
                //seta o Objeto como null para o GC limpar da memoria
                formNovaFormaPagamento = null;
                CBFormaPagamento.addItem(formaPagamento);
                CBFormaPagamento.setSelectedItem(formaPagamento);
            }
        };
        
    }
    
    private CallbackForm callbackTipoMovimento() {
        
        //Instanciando uma classe anonima
        return new CallbackForm<TipoMovimento>() {
            @Override
            public void fim(TipoMovimento tipomovimento) {
               formNovoTipoMovimento.setVisible(false);
                //seta o Objeto como null para o GC limpar da memoria
                formNovoTipoMovimento = null;
                cbNovoMovimento.addItem(tipomovimento);
                cbNovoMovimento.setSelectedItem(tipomovimento);
            }
        };
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormNovoLancamentosCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormNovoLancamentosCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormNovoLancamentosCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormNovoLancamentosCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormNovoLancamentosCaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<FormaPagamento> CBFormaPagamento;
    private javax.swing.JButton btnAdicionaTipoMovimento;
    private javax.swing.JButton btnAdicionaTipoPagamento;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvarNovoLancamento;
    private javax.swing.JComboBox<TipoMovimento> cbNovoMovimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelError;
    private javax.swing.JFormattedTextField txtValorLancamento;
    private javax.swing.JTextField txtobservacao;
    // End of variables declaration//GEN-END:variables

    private NumberFormatter getFormatoMoeda() {
        Locale locale = new Locale("pt", "BR");
        
        DecimalFormatSymbols dfs = new DecimalFormatSymbols(locale);
        dfs.setDecimalSeparator(',');
        DecimalFormat decimalFormat = new DecimalFormat(".##", dfs);
        NumberFormatter numberFormat = new NumberFormatter(decimalFormat);
        numberFormat.setFormat(decimalFormat);
        numberFormat.setAllowsInvalid(false);
        return numberFormat;
    }

}
