/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import CashFlowBO.ProdutoBO;
import ClashFlowObjeto.Produto;
import java.util.List;
import view.ProdutoTableModel;

/**
 *
 * @author Sonia
 */
public class FormConsultaProduto extends javax.swing.JFrame {

    private CallbackForm<Produto> callbackProduto;
    
    /**
     * Creates new form FormConsultaProduto
     */
    public FormConsultaProduto(CallbackForm<Produto> callbackProduto) {
        this.callbackProduto = callbackProduto;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtConsulta = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtConsultaProdutos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jLabel1.setText("Consulta Produtos");

        txtConsulta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtConsulta.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnPesquisar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1476299144_search.png"))); // NOI18N
        btnPesquisar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        JtConsultaProdutos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JtConsultaProdutos.setModel(new ProdutoTableModel());
        JtConsultaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtConsultaProdutosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JtConsultaProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtConsulta)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
               
        String nome = txtConsulta.getText();
             
        ProdutoBO produtoBO = new ProdutoBO();
        List<Produto> produtos = produtoBO.pesquisa(nome);
        JtConsultaProdutos.setModel(new ProdutoTableModel(produtos));
        JtConsultaProdutos.repaint();
    
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void JtConsultaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtConsultaProdutosMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2) {
            int row = JtConsultaProdutos.rowAtPoint(evt.getPoint());
           Produto produto = ((ProdutoTableModel) JtConsultaProdutos.getModel()).getValueAt(row);
           
           if(callbackProduto != null) {
               callbackProduto.fim(produto);
           }
            
        }
        
    }//GEN-LAST:event_JtConsultaProdutosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtConsultaProdutos;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtConsulta;
    // End of variables declaration//GEN-END:variables
}
